version: "3.9"

services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    volumes: 
      - ./.dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: br-app
      MYSQL_USER: api
      MYSQL_PASSWORD: dbpw123
    expose: 
      - "3306"
    networks: 
      - internal

  api:
    build: api/
    image: rstum/br-api
    ports:
      - "8084:8084"
    links: 
      - mysql
    depends_on:
      - mysql
    networks: 
      - internal
    
  web:
    build: web/
    image: rstum/br-web
    ports:
      - "80:80"
    
networks: 
  internal: